Initial Typography Stuff
Scout-NU/vital-site pull request #31
Opened 2021-03-25 23:17 UTC by sreya-kata

Did the following:
- took out max-width in "layout.js" so content starts at left side of page
- added "Work Sans" in gatsby-config and used as body font in "layout.css"
- downloaded 3 Futura variations (medium, bold, and heavy) and made typefaces for it in "typefaces.css"
- centralized fonts in "typography.js" with styled-components for h1, h2, h3, and p tags
- referenced styled-components in homepage file (shown below)
![types](https://user-images.githubusercontent.com/60420625/112555487-ace57480-8d9e-11eb-9cbe-b15e6263dd34.jpg)

2021-03-26 01:18 UTC, josephmannis requested changes
Just a few things, looks great otherwise – nice organization

2021-03-26 01:18 UTC, josephmannis commented on src/constants/typography.js
> +  h1: `calc(40px + (90 - 40) * ((100vw - 320px) / (1440 - 320)))`,
When you squish this header it does this, can you give it some leading please?

![image](https://user-images.githubusercontent.com/29356116/112563024-f50c9300-8dae-11eb-94ee-db99904dfc0d.png)

2021-03-26 01:18 UTC, josephmannis commented on src/constants/typography.js
> +  workSans: `'Work Sans', sans-serif`,
Generally a trend here is to name these like `body`, `header`, etc. Because if the fonts ever change the variable names no longer make sense

2021-03-26 01:18 UTC, josephmannis commented on src/constants/typography.js
> +  p: `calc(14px + (16 - 14) * ((100vw - 320px) / (1440 - 320)))`,
https://github.com/Scout-NU/vital-site/pull/32#discussion_r601940526

2021-03-26 01:18 UTC, josephmannis commented on src/constants/typography.js
> +  line-height: 60px;
This might stand to scale like font size, but usually that only applies to body font – I would check with Riha here

2021-03-26 01:18 UTC, josephmannis commented on src/pages/index.js
> +      <div style={{ maxWidth: `300px`, marginBottom: `1.45rem` }}>
https://github.com/Scout-NU/vital-site/pull/32#discussion_r601935593

2021-03-26 01:22 UTC, josephmannis commented on src/constants/typography.js
> +  h1: `calc(40px + (90 - 40) * ((100vw - 320px) / (1440 - 320)))`,
Upon further inspection this is a Safari bug, check the following recording:

https://user-images.githubusercontent.com/29356116/112563575-05713d80-8db0-11eb-9a28-750391873cd3.mov

My suspicion is that there is something weird going on with gatsby + styled components + the way styled components does browser fallbacks for CSS

2021-03-28 21:11 UTC, sreya-kata commented
- gave new variables names as well as made variables for breakpoints and font sizes
- added another type component for lowercase headings
- took out inline styling

2021-03-29 16:52 UTC, josephmannis requested changes
Looks good, please just check with Riha about line heights. Feel free to merge after the key fix!

2021-03-29 16:52 UTC, josephmannis commented on src/components/what-we-do/history/history.js
> +          <HLower>{milestone.title}</HLower>
🔑

2021-03-30 01:28 UTC, merged