API and Component Buildout for Homepage
Scout-NU/vital-site pull request #45
Opened 2021-03-27 01:34 UTC by sreya-kata

Did the following:
- reorganized component file structure so every utilized component has its own folder with a js file and (future) css file
- modified homepage content model in CMS to coincide with new design
- data fetched all CMS components of the homepage into a graphql query
- made initial components for all distinct homepage components based on hi-fis (hero, mission, inclusivity w/carousel, stay in the know, and final carousel)

Note: from the code, "mission", "inclusivity", and "stay in the know" seem similar but separate react components are made as they are each paired with another feature (ie: inclusivity has a passive carousel, "stay in the know" has a featured image, the stylings slightly differ). See hi-fi representation below:
![hifi](https://user-images.githubusercontent.com/60420625/112706488-e4295380-8e7a-11eb-8dbe-db17e6707191.jpg)

2021-03-27 21:25 UTC, josephmannis requested changes
Just a few things! Looks good otherwise

2021-03-27 21:25 UTC, josephmannis commented on src/components/homepage/carousel/carousel.js
> +          <div>
🔑

2021-03-27 21:25 UTC, josephmannis commented on src/components/homepage/carousel/carousel.js
> +            <a href={item.link}>Learn More</a>
Can you please add target="_blank"

2021-03-27 21:25 UTC, josephmannis commented on src/components/homepage/inclusivity/inclusivity.js
> +      <a href={ctaLink}>
🎯

2021-03-27 21:25 UTC, josephmannis commented on src/components/homepage/inclusivity/inclusivity.js
> +        <button type="button">{ctaTitle}</button>
Can you please add an aria label here?

2021-03-27 21:25 UTC, josephmannis commented on src/components/homepage/mission/mission.js
> +      <a href={ctaLink}>
🎯 and aria label for the button, ty!

2021-03-27 21:25 UTC, josephmannis commented on src/components/homepage/stay-in-the-know/stay-in-the-know.js
> +      <a href={ctaLink}>
Same here

2021-03-27 21:25 UTC, josephmannis commented on src/components/layout/layout.js
> -          maxWidth: 960,
Can you pull out the inline styles please?

2021-03-27 21:25 UTC, josephmannis commented on src/pages/index.js
> +      <Carousel
This is very neatly organized!

2021-03-27 21:25 UTC, josephmannis commented on src/components/homepage/carousel/carousel.js
> +            <a href={item.link}>Learn More</a>
Also, do these go to pages on the site or external links?

2021-03-27 22:22 UTC, sreya-kata commented on src/components/homepage/carousel/carousel.js
> +            <a href={item.link}>Learn More</a>
They're on the site. In the CMS, they're inputted as the name of page, but as the file name format (ie: "/get-involved")
Also I forgot to include the link in the query so adding that now^

2021-03-28 21:06 UTC, sreya-kata commented
- Added key to carousel item by also adding a separate react component for a single carousel item
- Added target and rel attributes to links
- Added aria-labels to buttons

2021-03-29 17:23 UTC, josephmannis approved these changes
There's a warning in the console for an unused import. Can you please clean that up, then everything should be good!

2021-03-29 17:50 UTC, merged