Initial Pages and Styled Components Plugin
Scout-NU/vital-site pull request #9
Opened 2021-03-12 00:50 UTC by sreya-kata

- Added initial pages + placeholder text for "our team", "what we do", "what's happening", and "get involved" pages
- Removed extra pages of "using-typescript" and "page-2"
- Added styled-components plugin to gatsby-config and package for styling later

2021-03-12 16:19 UTC, josephmannis requested changes
Routing looks good! Just one comment on the component structure.

2021-03-12 16:19 UTC, josephmannis commented on src/pages/what-we-do.js
> +const WhatWeDo = (props) => {
My only comment here is definitely use container components. The structure would be like this:

```
// This takes the props from gatsby
function WhatWeDoContainer(data) {
    // This takes a specific set of props that are human readable
    return <WhatWeDo title={data.title} cards={data.cards} ... />
}
```

2021-03-19 21:57 UTC, sreya-kata commented
- added component structure to "what-we-do" -> will do for other page structures as well
- will look into container components for future use when data/components get more complicated

2021-03-21 00:10 UTC, josephmannis commented on src/components/what-we-do/history.js
> +    <div>
Just a little thing, you can use a react fragment instead of a div if you don't need the div explicitly. You can just replace the div with `<> </>`

2021-03-21 00:11 UTC, josephmannis reviewed
One or two optional comments, otherwise looks good!

2021-03-21 00:11 UTC, josephmannis commented on src/components/what-we-do/programming-card.js
> +      <Img className="featured" fluid={photo.fluid} alt={title} />
Is there alt text hooked up in the CMS?

2021-03-21 15:16 UTC, merged